class AuthError(Exception):
    pass

class StorageError(Exception):
    pass